# Generated by Django 2.2.7 on 2019-12-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
