# Generated by Django 2.2.7 on 2019-12-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_post_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'published')], default='d', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='나 한문장으로 적어주세요', verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(help_text='닉네임을 정해주세요', max_length=100, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='나의 특징을 태그', max_length=50),
        ),
    ]
